[project]
name = "obsidian-thoughtagent"
version = "0.1.0"
description = "Autonomous Multi-Agent Obsidian Research Agent"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "langchain",
    "langchain-core",
    "langchain-openai",
    "langchain-ollama",
    "langgraph",
    "tavily-python",
    "duckduckgo-search",
    "python-dotenv"
    'duckduckgo_search'
]

[tool.uv]
package = false
